# Generated by Django 3.2.20 on 2023-10-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_assessmentworkflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentworkflow',
            name='student_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
