# Generated by Django 3.2.20 on 2023-10-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_assessmentworkflow_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentworkflow',
            name='student_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
